import 'package:get/get.dart';

class LocalLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'app_name': 'VRoomZ',
      'welcome': 'Welcome to VRoomZ',
      'start': 'Start using',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'phone': 'Phone number',
      'password': 'Password',
      'passport': 'Passport',
      'driving_license': 'Driving License',
      'company_license': 'Company License',
      'customer': 'Customer',
      'delivery_driver': 'Delivery Driver',
      'tow_truck_driver': 'Tow Truck Driver',
      'first_name': 'First name',
      'last_name': 'Last name',
      'already_have_account_click': 'Already have account? Click',
      'dont_have_account_click': "Don't have account? Click",
      'sign_up_to_continue': 'Sign up to Continue',
      'login_to_continue': 'Login to Continue',
      'sign_in_with_google': 'Sign in with Google',
      'sign_in_with_Apple': 'Sign in with Apple',
      'register': 'Register',
      'wallet': 'Wallet',
      'drop_point': 'Drop Point',
      'complains': 'Complains',
      'support': 'Support',
      'delivery': 'Delivery',
      'tow_truck': 'Tow Truck',
      'order_code': 'Order Code:',
      'on_the_way': 'On the way',
      'current_location': 'Current Location',
      'thornridge_cir_shiloh_hawaii': 'Thornridge Cir. Shiloh, Hawaii',
      'history': 'History',
      'package': 'Package',
      'order': 'Order',
      'pick_up': 'Pick Up',
      'drop': 'Drop',
      'delivery_option': 'Delivery Option',
      'pick_a_driver': 'Pick a Driver',
      'settings': 'Settings',
      'account_settings': 'Account Settings',
      'rewards_points': 'Rewards Points',
      'pts': '15 Pts',
      'change_password': 'Change Password',
      'subscription': 'Subscription',
      'edit_profile': 'Edit Profile',
      'switch_language': 'Switch language',
      'privacy_policy': 'Privacy Policy',
      'log_out': 'Log out',
      'delete_my_account': 'Delete my account',
      'old_password': 'Old Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'save': 'Save',
      'profile': 'Profile',
      'name': 'Name',
      'username': 'Username',
      'search': 'Search...',
      'payment_issue': 'Payment Issue',
      'driver_attitude': 'Driver Attitude',
      'the_driver_take_long_time_to_get_to_me':
          'The driver take long time to get to me',
      'where_is_my_package?': 'Where Is my package?',
      'the_order_missing': 'The order missing',
      'i_had_a_problem_when_my_order_was_shipped':
          'I had a problem when my order was shipped',
      'write_complains': 'Write Complains',
      'please_enter_your_order_no': 'Please enter your order no.',
      'order_no': 'Order No.',
      'Write_your_complain': 'Write your complain',
      'write': 'Write...',
      'send': 'Send',
      'your_complains': 'Your Complains',
      'inProcess': 'In process',
      'complete': 'Complete',
      'card': 'Card',
      'select_your_card': 'Select your card',
      'CREDIT': 'CREDIT',
      'enter_card_details': 'Enter card details',
      'card_name': 'Card name',
      'card_number': 'Card number',
      'expiry_date': 'Expiry date',
      'cvv': 'CVV',
      'i_agree_to_the': 'I agree to the',
      'terms_and_conditions': 'Terms and Conditions',
      'save_card_details': 'Save card details',
      'pay_now': 'PAY NOW',
      'delivery_details': 'Delivery Details',
      'davidson_edgar': 'Davidson Edgar',
      '20_deliveries': '20 Deliveries',
      'pickup_location': 'Pickup Location',
      'delivery_location': 'Delivery Location',
      'what_you_are_sending': 'What you are sending',
      'receipient': 'Receipient',
      'receipient_contact_number': 'Receipient contact number',
      'payment': 'Payment',
      'fee': 'Fee:',
      'pickup_images': 'Pickup image(s)',
      'view_map_route': 'View Map Route',
      'packages_details': 'Packages Details',
      'rider': 'Rider',
      'jacob_jones': 'Jacob Jones',
      'accept': 'Accept',
      '5_Min_arriving': '5 Min arriving',
      'tracking_id': 'Tracking ID',
      'departure': 'Departure',
      'arrival': 'Arrival',
      'gtv_machines': 'GVT Machines',
      'efv_lane': 'EFV Lane',
      'price': 'Price',
      'tax': 'Tax',
      'total': 'Total',
      'ipay': 'iPay',
      'gpay': 'gPay',
      'add_your_card': 'Add your card',
      'cash': 'Cash',
      'check_out': 'Check Out',
      'available_requests': 'Available Requests',
      'view_all': 'View All',
      'pickup': 'pickup',
      'reject': 'Reject',
      'electronics_gadgets': 'Electronics/Gadgets',
      'receipient_paul_pogba': 'Receipient: Paul Pogba',
      'maryland_bustop_anthony_ikeja': 'Maryland bustop, Anthony Ikeja',
      'available_balance': 'Available balance',
      'where_to': 'Where to?',
      'box_text_1': 'you have to pay the amount to continue getting orders',
      'box_text_2':
          'you have to update your details to continue getting orders',
      'title': "Would you like to specify direction for deliveries?",
      'faq_q1': 'What technologies did you use to build this portfolio?',
      'faq_a1':
          'I used Flutter with Dart, integrated custom themes, and followed responsive design principles.',
      'faq_q2': 'Can I contact you for freelance or collaboration?',
      'faq_a2':
          'Absolutely! Feel free to reach out through the contact section or email.',
      'faq_q3': 'Is this portfolio responsive on mobile and desktop?',
      'faq_a3':
          'Yes, the layout adapts smoothly to all screen sizes using Flutter’s built-in responsiveness.',
      'faq_q4': 'Do you provide source code or GitHub access?',
      'faq_a4':
          'I may share it on GitHub soon. Stay tuned or feel free to ask me directly!',
      'faq_title': 'Answers to the most common questions',
      'faq_more_questions': 'Have more questions?',
      'faq_input_question': 'Your Question',
      'faq_input_answer': 'Your Answer',

    },
    'ar_SA': {
      'app_name': 'فرومز',
      'welcome': 'مرحبن بك في فرومز',
      'start': 'تسجيل دخول لإن',
      'login': 'تسجيل دخول',
      'signup': 'تسجيل الدخول',
      'email': 'إيميل',
      'phone': 'رقم الهاتف',
      'password': 'كلمة المرور',
      'passport': 'جواز السفر',
      'driving_license': 'رخصة القيادة',
      'company_license': 'رخصة الشركة',
      'customer': 'زبون',
      'delivery_driver': 'سائق التوصيل',
      'tow_truck_driver': 'سائق شاحنة السحب',
      'first_name': 'إسم عائلة',
      'last_name': 'الإسم الإول',
      'already_have_account_click': 'لدي حساب ؟',
      'dont_have_account_click': ' ليس لدي حساب ؟',
      'sign_up_to_continue': 'إنشاء حساب جديد',
      'login_to_continue': 'تسجيل دخول',
      'sign_in_with_google': 'Google تسجيل دخول بستخدام ',
      'sign_in_with_Apple': 'Apple تسجيل دخول بستخدام ',
      'register': 'إنشاء حساب جديد',
      'wallet': 'محفظة',
      'drop_point': 'طلب توصيل',
      'complains': 'الشكاو',
      'support': 'إستفسارات',
      'delivery': 'مندوب',
      'tow_truck': 'سطحه',
      'order_code': ':رمز الطلبية',
      'on_the_way': 'في الطريق',
      'current_location': 'القنوان',
      'thornridge_cir_shiloh_hawaii': 'العين الطوية ،شارع زاخر بيت رقم',
      'history': 'الطلبيات السابقة ',
      'package': 'الصفحة',
      'order': 'طلب',
      'pick_up': 'موقع الإستلام',
      'drop': 'موقع التسليم',
      'delivery_option': 'خيار التوصيل',
      'pick_a_driver': 'اختر السائق',
      'settings': 'الإعدادات',
      'account_settings': 'إعدادات الحساب',
      'rewards_points': 'نقاط المكافآت',
      'pts': '15 نقاط',
      'change_password': 'تغيير كلمة المرور',
      'subscription': 'الاشتراك',
      'edit_profile': 'تعديل الملف الشخصي',
      'switch_language': 'تغيير اللغة',
      'privacy_policy': 'سياسة الخصوصية',
      'log_out': 'تسجيل خروج',
      'delete_my_account': 'حذف الحساب',
      'old_password': 'كلمة المرور القديمة',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تكرار كلمة المرور',
      'save': 'حفظ',
      'profile': 'الملف الشخصي',
      'name': 'الاسم',
      'username': 'اسم المستخدم',
      'search': 'ابحث...',
      'payment_issue': 'مشكلة في الدفع',
      'driver_attitude': 'سلوك السائق',
      'the_driver_take_long_time_to_get_to_me': 'تأخير في الوصول',
      'where_is_my_package?': 'أين طلبيتي؟',
      'the_order_missing': 'الطلب مفقود',
      'i_had_a_problem_when_my_order_was_shipped': 'واجهت مشكلة عند الشحن',
      'write_complains': 'اكتب الشكوى',
      'please_enter_your_order_no': 'أدخل رقم الطلب',
      'order_no': 'رقم الطلب',
      'Write_your_complain': 'اكتب شكواك',
      'write': 'اكتب...',
      'send': 'إرسال',
      'your_complains': 'شكاويك',
      'inProcess': 'قيد المعالجة',
      'complete': 'مكتمل',
      'card': 'البطاقة',
      'select_your_card': 'اختر بطاقتك',
      'CREDIT': 'بطاقة ائتمان',
      'enter_card_details': 'أدخل تفاصيل البطاقة',
      'card_name': 'اسم البطاقة',
      'card_number': 'رقم البطاقة',
      'expiry_date': 'تاريخ الانتهاء',
      'cvv': 'رمز التحقق',
      'i_agree_to_the': 'أوافق على',
      'terms_and_conditions': 'الشروط والأحكام',
      'save_card_details': 'حفظ تفاصيل البطاقة',
      'pay_now': 'ادفع الآن',
      'delivery_details': 'تفاصيل التوصيل',
      'davidson_edgar': 'ديفيدسون إدغار',
      '20_deliveries': '20 عملية توصيل',
      'pickup_location': 'موقع الاستلام',
      'delivery_location': 'موقع التوصيل',
      'what_you_are_sending': 'ماذا ترسل',
      'receipient': 'المستلم',
      'receipient_contact_number': 'رقم المستلم',
      'payment': 'الدفع',
      'fee': 'الرسوم:',
      'pickup_images': 'صور الاستلام',
      'view_map_route': 'عرض مسار الخريطة',
      'packages_details': 'تفاصيل الطرود',
      'rider': 'السائق',
      'jacob_jones': 'يعقوب جونز',
      'accept': 'قبول',
      '5_Min_arriving': 'سيصل خلال 5 دقائق',
      'tracking_id': 'معرّف التتبع',
      'departure': 'المغادرة',
      'arrival': 'الوصول',
      'gtv_machines': 'آلات GTV',
      'efv_lane': 'شارع EFV',
      'price': 'السعر',
      'tax': 'الضريبة',
      'total': 'الإجمالي',
      'ipay': 'iPay',
      'gpay': 'gPay',
      'add_your_card': 'أضف بطاقتك',
      'cash': 'نقداً',
      'check_out': 'الدفع',
      'available_requests': 'الطلبات المتاحة',
      'view_all': 'عرض الكل',
      'pickup': 'استلام',
      'reject': 'رفض',
      'electronics_gadgets': 'إلكترونيات',
      'receipient_paul_pogba': 'المستلم: بول بوغبا',
      'maryland_bustop_anthony_ikeja': 'موقف ماريلاند، أنتوني إيكجا',
      'available_balance': 'الرصيد المتاح',
      'where_to': 'إلى أين؟',
      'box_text_1': 'يجب دفع الرسوم للاستمرار في استلام الطلبات',
      'box_text_2': 'يجب تحديث بياناتك للاستمرار في استلام الطلبات',
      'title': "هل ترغب في تحديد الاتجاه للتوصيلات؟",
      'faq_q1': 'ما هي التقنيات التي استخدمتها لبناء هذا البورتفوليو؟',
      'faq_a1': 'استخدمت فلاتر مع دارت، ودمجت سمات مخصصة، واتبعت مبادئ التصميم المتجاوب.',
      'faq_q2': 'هل يمكنني التواصل معك للعمل الحر أو التعاون؟',
      'faq_a2': 'بالتأكيد! لا تتردد في التواصل من خلال قسم الاتصال أو عبر البريد الإلكتروني.',
      'faq_q3': 'هل هذا البورتفوليو متجاوب على الجوال وسطح المكتب؟',
      'faq_a3': 'نعم، يتكيف التصميم بسلاسة مع جميع أحجام الشاشات باستخدام إمكانيات فلاتر.',
      'faq_q4': 'هل توفر الكود المصدري أو الوصول إلى GitHub؟',
      'faq_a4': 'قد أشاركه قريباً على GitHub. تابعني أو لا تتردد في سؤالي مباشرة!',
      'faq_title': 'إجابات على أكثر الأسئلة شيوعًا',
      'faq_more_questions': 'هل لديك المزيد من الأسئلة؟',
      'faq_input_question': 'سؤالك',
      'faq_input_answer': 'إجابتك',


    },
  };
}
